image: gcc

build:
  stage: build
  before_script:
    - echo "deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/ trusty main" >> /etc/apt/sources.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv B118CD3C377DF930EDD06C67084ECFC5828AB726
    - gpg --keyserver keyserver.ubuntu.com --recv "B118 CD3C 377D F930 EDD0  6C67 084E CFC5 828A B726"
    - apt-get update
    - apt-get -y install cmake libxml2-dev valgrind catch libasio-dev
  script:
    - cmake -DPYTHON_BINDINGS=OFF .
    - make -j$(nproc)
    - make test

#TODO: install and cache .ccache
